<?php
echo '{"users":[
            {
                "firstName":"Daniel",
                "lastName":"Newsom",
                "joined":{
                        "month":"June",
                        "day":12,
                        "year":1984
                        }
            },
            {
                "firstName":"Joanne",
                "lastName":"Newsom",
                "joined":{
                        "month":"December",
                        "day":13,
                        "year":1982
                        }
            }
      ]}';
?>